# Generated by Django 4.2.4 on 2023-09-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='blacklist',
        ),
    ]
