# Generated by Django 4.2.4 on 2023-09-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_suspiciouswebsite_delete_blacklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.AddField(
            model_name='profile',
            name='forget_password_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_reset_link_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='forget_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
