# Generated by Django 4.2.4 on 2023-10-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0005_remove_profile_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlinjectionWebsites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
